package com.dvdu.defects;

public enum ViewModes {
	VIEW_MODE_RGBA,
	VIEW_MODE_DEUTERANOPE,
	VIEW_MODE_PROTANOPE,
	VIEW_MODE_TRITANOPE,
	VIEW_MODE_CATARACT,
	VIEW_MODE_DIABETIC_RETINOPATHY,
	VIEW_MODE_RETINIS_PIGMENTOSA;
}
